package api

import (
	"bytes"
	"encoding/json"
	"fmt"
	"slices"
	"strings"

	"github.com/rs/zerolog"
)

// SpecVersion is the OpenAPI dialect the generated document declares.
const SpecVersion = "3.0.3"

// JSON Schema and OpenAPI keywords, named so a typo is a compile error rather
// than a silently malformed document.
const (
	kwType        = "type"
	kwRequired    = "required"
	kwDescription = "description"
	kwTitle       = "title"
	kwString      = "string"
)

// Schema component names, referenced from both the operations table and the
// components block.
const (
	schemaNote    = "Note"
	schemaDraft   = "Draft"
	schemaStatus  = "Status"
	schemaVersion = "Version"
	schemaError   = "Error"
)

// methodGet is the only HTTP method spelled repeatedly in the table below.
const methodGet = "get"

// specPath is the checked-in location of the generated document. The devctl
// `openapi` command writes here and CI diffs it, so a route added without
// regenerating fails the build.
const specPath = "docs/openapi.json"

// SpecPath returns the repository-relative path of the generated document.
func SpecPath() string { return specPath }

// operation describes one documented route.
type operation struct {
	Summary   string
	Responses map[string]string
	// Guarded marks routes that require the bearer token.
	Guarded bool
	// RequestSchema names a component schema for the request body, if any.
	RequestSchema string
	// ResponseSchema names a component schema for the 2xx body, if any.
	ResponseSchema string
	// ResponseIsArray wraps ResponseSchema in an array.
	ResponseIsArray bool
}

// operations is the documentation half of the route table in Router. Both are
// checked against each other by SpecDrift, so neither can drift silently.
var operations = map[string]map[string]operation{
	"/healthz": {methodGet: {
		Summary:        "Liveness probe. Always 200 while the process is running.",
		Responses:      map[string]string{"200": "the service is alive"},
		ResponseSchema: schemaStatus,
	}},
	"/readyz": {methodGet: {
		Summary:        "Readiness probe. Touches the store, so a broken dependency shows here.",
		Responses:      map[string]string{"200": "ready to serve", "503": "a dependency is unavailable"},
		ResponseSchema: schemaStatus,
	}},
	"/version": {methodGet: {
		Summary:        "Build provenance of the running binary.",
		Responses:      map[string]string{"200": "version and commit"},
		ResponseSchema: schemaVersion,
	}},
	"/v1/notes": {
		methodGet: {
			Summary:         "List every note, newest first.",
			Responses:       map[string]string{"200": "the notes"},
			ResponseSchema:  schemaNote,
			ResponseIsArray: true,
		},
		"post": {
			Summary:        "Create a note.",
			Guarded:        true,
			RequestSchema:  schemaDraft,
			ResponseSchema: schemaNote,
			Responses: map[string]string{
				"201": "the created note", "400": "validation failed", "401": "missing or bad token",
			},
		},
	},
	"/v1/notes/{id}": {
		methodGet: {
			Summary:        "Fetch one note by ID.",
			Responses:      map[string]string{"200": "the note", "404": "no note with that ID"},
			ResponseSchema: schemaNote,
		},
		"delete": {
			Summary: "Delete one note by ID.",
			Guarded: true,
			Responses: map[string]string{
				"204": "deleted", "401": "missing or bad token", "404": "no note with that ID",
			},
		},
	},
}

// Spec renders the OpenAPI document as indented JSON with a trailing newline,
// so the committed file is diff-stable.
func Spec() ([]byte, error) {
	paths := make(map[string]any, len(operations))
	for path, byMethod := range operations {
		methods := make(map[string]any, len(byMethod))
		for method, op := range byMethod {
			methods[method] = renderOperation(path, op)
		}
		paths[path] = methods
	}

	doc := map[string]any{
		"openapi": SpecVersion,
		"info": map[string]any{
			kwTitle:       "go-agents API",
			"version":     "1.0.0",
			kwDescription: "REST API over the notes domain. Generated by `devctl openapi` — never hand-edited.",
		},
		"paths": paths,
		"components": map[string]any{
			"securitySchemes": map[string]any{
				"bearerAuth": map[string]any{kwType: "http", "scheme": "bearer"},
			},
			"schemas": map[string]any{
				schemaNote: objectSchema(
					[]string{"id", kwTitle, "body", "created_at"},
					property("id", "server-assigned UUID"),
					property(kwTitle, "short label, 1-200 bytes after trimming"),
					property("body", "free text, up to 4096 bytes"),
					dateTimeProperty("created_at", "UTC creation timestamp"),
				),
				schemaDraft: objectSchema(
					[]string{kwTitle},
					property(kwTitle, "short label, 1-200 bytes after trimming"),
					property("body", "free text, up to 4096 bytes"),
				),
				schemaStatus: objectSchema([]string{"status"}, property("status", "probe result")),
				schemaVersion: objectSchema(
					[]string{"version", "commit"},
					property("version", "release version"),
					property("commit", "git commit, with -dirty when built from a dirty tree"),
				),
				schemaError: objectSchema([]string{"error"}, property("error", "human-readable reason")),
			},
		},
	}

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("encode openapi document: %w", err)
	}
	return buf.Bytes(), nil
}

func renderOperation(path string, op operation) map[string]any {
	responses := make(map[string]any, len(op.Responses))
	for code, desc := range op.Responses {
		r := map[string]any{kwDescription: desc}
		switch {
		case code >= "400":
			r["content"] = jsonContent(ref(schemaError))
		case op.ResponseSchema != "" && code != "204":
			schema := ref(op.ResponseSchema)
			if op.ResponseIsArray {
				schema = map[string]any{kwType: "array", "items": schema}
			}
			r["content"] = jsonContent(schema)
		}
		responses[code] = r
	}

	out := map[string]any{"summary": op.Summary, "responses": responses}
	if op.Guarded {
		out["security"] = []any{map[string]any{"bearerAuth": []any{}}}
	}
	if op.RequestSchema != "" {
		out["requestBody"] = map[string]any{
			kwRequired: true,
			"content":  jsonContent(ref(op.RequestSchema)),
		}
	}
	if strings.Contains(path, "{id}") {
		out["parameters"] = []any{map[string]any{
			"name": "id", "in": "path", kwRequired: true,
			"schema": map[string]any{kwType: kwString},
		}}
	}
	return out
}

func ref(name string) map[string]any {
	return map[string]any{"$ref": "#/components/schemas/" + name}
}

func jsonContent(schema map[string]any) map[string]any {
	return map[string]any{"application/json": map[string]any{"schema": schema}}
}

// property builds a string-typed schema property. Every property in this
// document is a string; add a typed variant when that stops being true.
func property(name, desc string) [2]any {
	return [2]any{name, map[string]any{kwType: kwString, kwDescription: desc}}
}

func dateTimeProperty(name, desc string) [2]any {
	return [2]any{name, map[string]any{kwType: kwString, "format": "date-time", kwDescription: desc}}
}

func objectSchema(required []string, props ...[2]any) map[string]any {
	properties := make(map[string]any, len(props))
	for _, p := range props {
		properties[p[0].(string)] = p[1]
	}
	return map[string]any{kwType: "object", kwRequired: required, "properties": properties}
}

// SpecDrift reports routes bound by Router but undocumented in operations, and
// vice versa. It is the guard that keeps the generated document honest: adding
// a handler without documenting it fails here rather than shipping silently.
func SpecDrift() (missingDocs, missingRoutes []string) {
	documented := map[string]bool{}
	for path, byMethod := range operations {
		for method := range byMethod {
			documented[strings.ToUpper(method)+" "+path] = true
		}
	}

	bound := map[string]bool{}
	// A throwaway Server: Router only reads the route table, never the store.
	for _, ri := range NewServer(nil, zerolog.Nop(), "").Router().Routes() {
		bound[ri.Method+" "+ginPathToOpenAPI(ri.Path)] = true
	}

	for k := range bound {
		if !documented[k] {
			missingDocs = append(missingDocs, k)
		}
	}
	for k := range documented {
		if !bound[k] {
			missingRoutes = append(missingRoutes, k)
		}
	}
	slices.Sort(missingDocs)
	slices.Sort(missingRoutes)
	return missingDocs, missingRoutes
}

// ginPathToOpenAPI converts gin's `:id` parameter syntax to OpenAPI's `{id}`.
func ginPathToOpenAPI(p string) string {
	parts := strings.Split(p, "/")
	for i, seg := range parts {
		if after, ok := strings.CutPrefix(seg, ":"); ok {
			parts[i] = "{" + after + "}"
		}
	}
	return strings.Join(parts, "/")
}
